#ifndef _THOMSON_CODES_H
#define _THOMSON_CODES_H 1



#define THOMSON_MAX_BITS	25
#define THOMSON_START_THR	50
#define THOMSON_HOLD_THR	9000

#define THOMSON_HIGH_THR	500//600
#define THOMSON_REPEAT_THR	6000




#define START_DEC_THRESHOLD (uint16_t)THOMSON_START_THR
#define SIG_HOLD_THRS		(uint16_t)THOMSON_HOLD_THR
#define SIG_MAX_BITS		(uint8_t)THOMSON_MAX_BITS
#define SIG_HIGH_THR		(uint16_t)THOMSON_HIGH_THR
#define SIG_REPEAT_THR		(uint16_t)THOMSON_REPEAT_THR
#define SIG_QALIF_THR		(uint8_t)2


#endif /* _THOMSON_CODES_H */
